# ~/.tmuxinator/sample.yml
# Launches the dev environment (gulp, jekyll and a working shell)

name: dev-codemotion
# root: ~/

windows:
  - editor:
      layout: main-vertical
      panes:
        - # empty shell
        - gulp
        - ./bin/jekyll
