# ~/.tmuxinator/sample.yml
# Launches the dev environment (gulp, jekyll and a working shell)
# tmuxinator create dev
# tmuxinator open dev

name: dev
root: ~/

windows:
  - editor:
      layout: main-vertical
      panes:
        - # empty shell
        - gulp
        - ./bin/jekyll
